steps:
  - name: 'adoptopenjdk/openjdk11'
    entrypoint: './sbt'
    args: ['test']

  - name: 'adoptopenjdk/openjdk11'
    entrypoint: './sbt'
    args: ['clean']

  - name: 'gcr.io/k8s-skaffold/pack'
    entrypoint: 'pack'
    args: ['build', '--builder=paketobuildpacks/builder-jammy-base', '--publish', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest']

  - name: 'ghcr.io/jamesward/easycloudrun'
    entrypoint: 'multiregion'
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'BUILD_ID=$BUILD_ID'
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'IMAGE_NAME=$REPO_NAME'
      - 'IMAGE_VERSION=$COMMIT_SHA'
      - 'DEPLOY_OPTS=--memory=512Mi --execution-environment=gen2'
      - 'DOMAINS=javadocs.dev'

options:
  machineType: 'N1_HIGHCPU_32'
