[[build.env]]
name = "BP_JVM_VERSION"
value = "21"

[[build.env]]
name = "BPE_OVERRIDE_BPL_JVM_THREAD_COUNT"
value = "50"

[[build.env]]
name = "BP_NATIVE_IMAGE"
value = "true"

[[build.env]]
name = "BP_SBT_BUILD_ARGUMENTS"
value = "stage"

[[build.env]]
name = "BP_SBT_BUILT_ARTIFACT"
value = "target/universal/stage/lib/*.jar"

[[build.env]]
name = "BP_NATIVE_IMAGE_BUILT_ARTIFACT"
value = "default.javadoccentral-**-launcher.jar"

[[build.env]]
name = "BP_BINARY_COMPRESSION_METHOD"
value = "upx"

[[build.env]]
name = "BP_NATIVE_IMAGE_BUILD_ARGUMENTS"
value = "--install-exit-handlers -H:+UnlockExperimentalVMOptions --strict-image-heap --initialize-at-build-time=org.apache.commons.compress --initialize-at-build-time=org.slf4j.simple.SimpleLogger --initialize-at-build-time=org.slf4j.simple.SimpleLoggerConfiguration --initialize-at-build-time=org.slf4j.simple.OutputChoice --initialize-at-build-time=org.slf4j.simple.OutputChoice$OutputChoiceType --initialize-at-run-time=io.netty.handler.ssl.BouncyCastleAlpnSslUtils --initialize-at-run-time=io.netty.channel.kqueue.KQueueEventLoop --initialize-at-run-time=io.netty.channel.epoll.EpollEventLoop"
